replicaCount: 2

image:
  repository: docker.io/amolmedo/service-a
  tag: "test-1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9898

resources:
  limits:
    cpu: "300m"
    memory: "512Mi"
  requests:
    cpu: "150m"
    memory: "256Mi"

env:
  - name: ENVIRONMENT
    value: "testing"

