spec:
  source:
    repoURL: https://github.com/AMOlmedo/infra-gitops.git
    targetRevision: main
    path: charts/service-a   
    helm:
      valueFiles:
        - environments/dev/values-service-a.yaml

